services:
  - type: web
    name: my-service
    env: node
    buildCommand: npm install --legacy-peer-deps && npm run build
    startCommand: npm start
    plan: free
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
